server:
  port: ${SPRING_SERVER_PORT:${SIMULATOR_PORT:8081}}
  shutdown: graceful

spring:
  main:
    banner-mode: console
  lifecycle:
    timeout-per-shutdown-phase: 25s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

controller:
  url: ${CONTROLLER_URL}

app:
  simulation:
    batch-size: ${APP_BATCH_SIZE:500}
    device-count: 500
    frequency-seconds: 1
