# iot-data-gateway: base backend, NodePort service for external access.
resources:
  - ../../base/backend

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: iot-data-gateway
      - op: replace
        path: /metadata/labels/app
        value: iot-data-gateway
      - op: replace
        path: /spec/selector/matchLabels/app
        value: iot-data-gateway
      - op: replace
        path: /spec/template/metadata/labels/app
        value: iot-data-gateway
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: iot-data-gateway
      - op: replace
        path: /metadata/labels/app
        value: iot-data-gateway
      - op: replace
        path: /spec/selector/app
        value: iot-data-gateway
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30085

images:
  - name: iot-backend
    newName: cr.yandex/crppvev0ar439gma3l6q/iot-service/iot-data-gateway
    newTag: f95889dffc59dc8ca0711d5affa35d34c8e53106
