# iot-controller: base backend + HPA, only names and image differ.
resources:
  - ../../base/backend
  - ../../base/hpa

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: iot-controller
      - op: replace
        path: /metadata/labels/app
        value: iot-controller
      - op: replace
        path: /spec/selector/matchLabels/app
        value: iot-controller
      - op: replace
        path: /spec/template/metadata/labels/app
        value: iot-controller
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/name
        value: iot-controller
      - op: replace
        path: /metadata/labels/app
        value: iot-controller
      - op: replace
        path: /spec/selector/app
        value: iot-controller
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /metadata/name
        value: iot-controller-hpa
      - op: replace
        path: /spec/scaleTargetRef/name
        value: iot-controller

images:
  - name: iot-backend
    newName: cr.yandex/crppvev0ar439gma3l6q/iot-service/iot-controller
    newTag: 297d9c2410546e5aaf1de8908747f7a0b956c945
