global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iot-alerts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iot-alerts:8080' ]

  - job_name: 'iot-analytics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-analytics:8080']

  - job_name: 'iot-controller'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iot-controller:8080' ]

  - job_name: 'iot-data-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iot-data-gateway:8080' ]

  - job_name: 'iot-data-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iot-data-simulator:8080' ]

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
