apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: iot
data:
  fluent-bit.conf: |
    [SERVICE]
        flush 1
        log_level info
        parsers_file parsers.conf

    [INPUT]
        name tail
        path /var/log/containers/*.log
        multiline.parser docker, cri
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On

    [FILTER]
        name kubernetes
        match kube.*
        merge_log on
        keep_log off
        k8s-logging.parser on
        k8s-logging.exclude on

    [OUTPUT]
        name tcp
        match kube.*
        host logstash
        port 5044
        format json
        json_date_format iso8601

  parsers.conf: |
    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off