apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-analytics
  namespace: iot
  labels:
    app: iot-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-analytics
  template:
    metadata:
      labels:
        app: iot-analytics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: analytics
          image: ghcr.io/mooncake911/iot-service/iot-analytics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: iot-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
