server:
  port: ${SPRING_SERVER_PORT:${ANALYTICS_PORT:8083}}
  shutdown: graceful

spring:
  main:
    banner-mode: console
  lifecycle:
    timeout-per-shutdown-phase: 25s
  data:
    mongodb:
      uri: ${MONGO_ANALYTICS_URI:mongodb://admin:admin@localhost:27018/iot_analytics_db?authSource=admin}
  rabbitmq:
    x-queue-mode: lazy
    port: ${RABBIT_MQ_PORT:5672}
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

app:
  rabbitmq:
    chunk-size: 500
    exchange:
      data: iot.data.exchange
    analytics:
      queue:
        name: iot-analytics.queue
        ttl: 60000
      concurrency: 8
  analytics:
    default-method: Parallel
    default-window-seconds: 30
